### PR TITLE
Insert newline at end of generated files

### LINKED ISSUE #320: bug: files are missing final newlines
**Describe the bug**

Many linters and related tools expect newlines at the end of files. As far as I can tell, `ts-rs` does not add one to generated `.ts` files, which I wouldn't necessarily classify as a *bug* but I think that it's more surprising to not have one than to have one.

**To Reproduce**

Generate any new `.ts` files.

**Expected behavior**

Generated `.ts` files have a newline at the end.

**Screenshots**

N/A

**Version**

8.1.0

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by lucperkins**
## Goal

Closes #320

## Changes

How did you go about solving the problem?

## Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/Aleph-Alpha/ts-rs/blob/main/CONTRIBUTING.md).
- [x] If necessary, I have added documentation related to the changes made.
- [x] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Review by escritorio-gustavo — APPROVED** [review]
LGTM

File: ts-rs/tests/integration/docs.rs [hunk 1]
```diff
@@ -116,6 +116,7 @@ fn export_a() {
             "   */\n",
             "  name: string;\n",
             "};\n",
+            "\n",
```
Comment (escritorio-gustavo) [inline ts-rs/tests/integration/docs.rs:119]: The `format` feature removes the duplicated `\n`, no need to add it here

**Review by escritorio-gustavo — APPROVED** [review]
LGTM + CI passes

**Comment by escritorio-gustavo** [comment]
Thanks for the PR @lucperkins!
